Repository intuit/proof, pull requests merged in 2019-10, with the labels that each got.

#10 Decrease memory footprint of the applitools plugin
  plugins/applitools/src/main.ts
Labels: hacktoberfest, patch

#11 Add pull request gh action
  .github/workflows/pull-request.yml
  .github/workflows/push.yml
Labels: skip-release

#14 Add contributing setup info to the README #13
  README.md
Labels: documentation, skip-release

#21 Added README.md for add-all plugin
  plugins/add-all/README.md
Labels: documentation, skip-release

#20 Added README.md for applitools plugin
  plugins/applitools/README.md
Labels: documentation, skip-release

#19 Create README.md for config
  packages/config/README.md
Labels: documentation, skip-release

#18 added README.md file for babel plugin
  plugins/babel/README.md
Labels: documentation, skip-release

#17 added README.md file for console plugin
  plugins/console/README.md
Labels: documentation, skip-release

#16 Create README.md for junit plugin
  plugins/junit/README.md
Labels: documentation, skip-release

#15 Create README.md files for skip-tests plugin and test package
  packages/test/README.md
  plugins/skip-tests/README.md
Labels: documentation, skip-release

#23 Build docs site from plugin READMEs
  packages/docs/package.json
  packages/docs/scripts/build.js
  packages/docs/src/plugins/.gitignore
  packages/docs/src/plugins/add-all.md
  packages/docs/src/plugins/applitools.md
  packages/docs/src/plugins/babel.md
  packages/docs/src/plugins/console.md
  packages/docs/src/plugins/junit.md
  packages/docs/src/plugins/skip-tests.md
  plugins/accessibility/README.md
  yarn.lock
Labels: documentation, skip-release

#24 Issue 8 fix enabling default accessibility config
  plugins/accessibility/src/main.ts
Labels: patch

#28 move webdriveio to dependency
  packages/browser/package.json
  packages/core/package.json
  yarn.lock
Labels: patch

#29 Wait for Root To Exist
  packages/browser/src/main.ts
Labels: patch

#31 links don't work in peers
  plugins/accessibility/package.json
  plugins/add-all/package.json
  plugins/applitools/package.json
  plugins/babel/package.json
  plugins/console/package.json
  plugins/junit/package.json
  plugins/skip-tests/package.json
Labels: patch
