Repository intuit/proof, pull requests merged in 2019-09, with the labels that each got.

#4 Add a code of conduct and license file
  CODE_OF_CONDUCT.md
  LICENSE
Labels: skip-release

#5 update applitools docs
  packages/docs/src/plugins/applitools.md
Labels: documentation, skip-release

#6 Add hook for capabilities
  packages/browser/src/main.ts
Labels: patch
