Repository intuit/proof, pull requests merged in 2020-10, with the labels that each got.

#64 Adding Badges in README.md
  README.md
Labels: documentation, hacktoberfest, skip-release

#68 Fix #3: Add hooks documentation
  packages/docs/src/_sidebar.md
  packages/docs/src/api/hooks.md
Labels: documentation, skip-release

#67 Fix #63: Document writing custom plugins
  packages/docs/src/_sidebar.md
  packages/docs/src/plugins/Creating-new-plugin.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted, skip-release
